# Generated by Django 2.0.6 on 2019-05-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created', 'title')},
        ),
    ]
